#! LOGIN
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

###

#! USER DETAILS
GET http://127.0.0.1:8000/user_details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJfaWQiOjEsImVtYWlsIjoiYWRtaW5AZW1haWwuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImV4cCI6MTc2NTExNzMyOX0.sIzkHIsfpbTjAlXu0Qae-BXBNtx-D01p1qR-e7DIEJk

###

#! USERS
GET http://127.0.0.1:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJfaWQiOjEsImVtYWlsIjoiYWRtaW5AZW1haWwuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImV4cCI6MTc2NTExNzMyOX0.sIzkHIsfpbTjAlXu0Qae-BXBNtx-D01p1qR-e7DIEJk

###

#! MOVIES
GET http://127.0.0.1:8000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJfaWQiOjEsImVtYWlsIjoiYWRtaW5AZW1haWwuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImV4cCI6MTc2NTExNzMyOX0.sIzkHIsfpbTjAlXu0Qae-BXBNtx-D01p1qR-e7DIEJk