POST http://localhost:8000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJfaWQiOjEsImVtYWlsIjoiYWRtaW5AZW1haWwuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImV4cCI6MTc2NTExNzA5MX0.tcpqxCkRCHZjRUc2HxK0oQNuKYgsfm_wW3L4ACIkNww

{
  "username": "admin1",
  "email": "admin1@email.com",
  "password": "admin1123",
  "roles": ["ROLE_USER", "ROLE_ADMIN"]
}

###

#! LOGIN
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

###

#! USERS
GET http://127.0.0.1:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJfaWQiOjEsImVtYWlsIjoiYWRtaW5AZW1haWwuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImV4cCI6MTc2NTExNzA5MX0.tcpqxCkRCHZjRUc2HxK0oQNuKYgsfm_wW3L4ACIkNww